# Pandas Telemetry Processing

### Objective



- Pandas-based telemetry ingestion
- Time-indexing of telemetry data
- Query handling and filtering
- DataFrame creation and manipulation
- Timestamp conversion and management
- Time-range based telemetry selection
- Conditional data filtering
- Basic telemetry data inspection

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [19]:
telemetry_data = {
    "timestamp": [
        "2026-08-10 09:00:00",
        "2026-08-10 09:01:00",
        "2026-08-10 09:02:00",
        "2026-08-10 09:03:00",
        "2026-08-10 09:04:00"
    ],
    "temperature": [25.4, 26.1, 27.3, 28.0, 27.6],
    "pressure": [1012, 1011, 1010, 1009, 1010],
    "altitude": [120, 125, 130, 135, 132],
    "speed": [45, 47, 50, 52, 49]
}

df = pd.DataFrame(telemetry_data)

df

             timestamp  temperature  pressure  altitude  speed
0  2026-08-10 09:00:00         25.4      1012       120     45
1  2026-08-10 09:01:00         26.1      1011       125     47
2  2026-08-10 09:02:00         27.3      1010       130     50
3  2026-08-10 09:03:00         28.0      1009       135     52
4  2026-08-10 09:04:00         27.6      1010       132     49

In [20]:
df.to_csv("telemetry_data.csv", index=False)

print("Telemetry data saved successfully.")

Telemetry data saved successfully.

In [21]:
telemetry_df = pd.read_csv("telemetry_data.csv")

telemetry_df

             timestamp  temperature  pressure  altitude  speed
0  2026-08-10 09:00:00         25.4      1012       120     45
1  2026-08-10 09:01:00         26.1      1011       125     47
2  2026-08-10 09:02:00         27.3      1010       130     50
3  2026-08-10 09:03:00         28.0      1009       135     52
4  2026-08-10 09:04:00         27.6      1010       132     49

In [5]:
print("Rows:", telemetry_df.shape[0])
print("Columns:", telemetry_df.shape[1])

print("\nColumn names:")
print(telemetry_df.columns.tolist())

Rows: 5
Columns: 5

Column names:
['timestamp', 'temperature', 'pressure', 'altitude', 'speed']

In [15]:
telemetry_df["timestamp"] = pd.to_datetime(telemetry_df["timestamp"])

print(telemetry_df["timestamp"])

0   2026-08-10 09:00:00
1   2026-08-10 09:01:00
2   2026-08-10 09:02:00
3   2026-08-10 09:03:00
4   2026-08-10 09:04:00
Name: timestamp, dtype: datetime64[us]

In [16]:
telemetry_df = telemetry_df.set_index("timestamp")

telemetry_df

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:00:00         25.4      1012       120     45
2026-08-10 09:01:00         26.1      1011       125     47
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:03:00         28.0      1009       135     52
2026-08-10 09:04:00         27.6      1010       132     49

In [27]:
telemetry_df["timestamp"] = pd.to_datetime(telemetry_df["timestamp"])

telemetry_df = telemetry_df.set_index("timestamp")

telemetry_df

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:00:00         25.4      1012       120     45
2026-08-10 09:01:00         26.1      1011       125     47
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:03:00         28.0      1009       135     52
2026-08-10 09:04:00         27.6      1010       132     49

In [28]:
# Time-Based Query Handling

time_range_data = telemetry_df.loc[
    "2026-08-10 09:01:00":"2026-08-10 09:03:00"
]

time_range_data

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:01:00         26.1      1011       125     47
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:03:00         28.0      1009       135     52

In [26]:
print(telemetry_df.index)
print(telemetry_df.index.dtype)
print(type(telemetry_df.index))

RangeIndex(start=0, stop=5, step=1)
int64
<class 'pandas.RangeIndex'>

In [29]:
# Filtering telemetry data
filtered_data = telemetry_df[
    telemetry_df["temperature"] > 27
]

filtered_data

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:03:00         28.0      1009       135     52
2026-08-10 09:04:00         27.6      1010       132     49

In [30]:
# Sorting telemetry data by temperature
sorted_data = telemetry_df.sort_values(by="temperature", ascending=False)

sorted_data

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:03:00         28.0      1009       135     52
2026-08-10 09:04:00         27.6      1010       132     49
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:01:00         26.1      1011       125     47
2026-08-10 09:00:00         25.4      1012       120     45

In [31]:
# Sorting telemetry data by temperature
sorted_data = telemetry_df.sort_values(by="temperature", ascending=False)

sorted_data

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:03:00         28.0      1009       135     52
2026-08-10 09:04:00         27.6      1010       132     49
2026-08-10 09:02:00         27.3      1010       130     50
2026-08-10 09:01:00         26.1      1011       125     47
2026-08-10 09:00:00         25.4      1012       120     45

In [32]:
# Statistical summary of telemetry data
summary = telemetry_df[["temperature", "pressure", "altitude", "speed"]].describe()

summary

       temperature     pressure   altitude      speed
count     5.000000     5.000000    5.00000   5.000000
mean     26.880000  1010.400000  128.40000  48.600000
std       1.089495     1.140175    5.94138   2.701851
min      25.400000  1009.000000  120.00000  45.000000
25%      26.100000  1010.000000  125.00000  47.000000
50%      27.300000  1010.000000  130.00000  49.000000
75%      27.600000  1011.000000  132.00000  50.000000
max      28.000000  1012.000000  135.00000  52.000000

In [33]:
# Checking missing values
missing_values = telemetry_df.isnull().sum()

missing_values

temperature    0
pressure       0
altitude       0
speed          0
dtype: int64

In [34]:
# Checking temperature range
temperature_check = telemetry_df[
    (telemetry_df["temperature"] < 20) |
    (telemetry_df["temperature"] > 40)
]

temperature_check

Empty DataFrame
Columns: [temperature, pressure, altitude, speed]
Index: []

In [36]:
# Checking pressure range
pressure_check = telemetry_df[
    (telemetry_df["pressure"] < 950) |
    (telemetry_df["pressure"] > 1010)
]

pressure_check

                     temperature  pressure  altitude  speed
timestamp
2026-08-10 09:00:00         25.4      1012       120     45
2026-08-10 09:01:00         26.1      1011       125     47

In [37]:
# Checking altitude and speed ranges

altitude_check = telemetry_df[
    (telemetry_df["altitude"] < 0) |
    (telemetry_df["altitude"] > 500)
]

speed_check = telemetry_df[
    (telemetry_df["speed"] < 0) |
    (telemetry_df["speed"] > 200)
]

print("Altitude out-of-range records:")
print(altitude_check)

print("\nSpeed out-of-range records:")
print(speed_check)

Altitude out-of-range records:
Empty DataFrame
Columns: [temperature, pressure, altitude, speed]
Index: []

Speed out-of-range records:
Empty DataFrame
Columns: [temperature, pressure, altitude, speed]
Index: []

In [38]:
# Saving processed telemetry data

telemetry_df.to_csv("processed_telemetry.csv")

print("Processed telemetry data saved successfully.")

Processed telemetry data saved successfully.

In [39]:
# Final telemetry processing summary

print("Total records:", len(telemetry_df))
print("Columns:", list(telemetry_df.columns))
print("Data shape:", telemetry_df.shape)
print("Missing values:", telemetry_df.isnull().sum().sum())
print("Duplicate records:", telemetry_df.duplicated().sum())

Total records: 5
Columns: ['temperature', 'pressure', 'altitude', 'speed']
Data shape: (5, 4)
Missing values: 0
Duplicate records: 0